### PR TITLE
Make CaseClassSerializer immuable

### PR DESCRIPTION
**Pull request by novakov-alexey**
update to Issue #112 
@sonowz - could you check if such fix fixes your original problem as well?

### CODE REVIEW

**Comment by sonowz** [comment]
Yes I can confirm this fixes my problem. Great!

However, I want to note that some users could provide thread-unsafe TypeSerializers using implicit givens, and still have the problem pop up regardless of the fix. Wouldn't you mind also merging #111, so that such minor cases can be covered? After all, calling `.duplicate()` is not that big deal because it is only called in the initialization phase of Flink app.

**Comment by novakov-alexey** [comment]
Ok, thanks, I will merge this then.

I do not want to call "duplicate" on the serializers, because those serializers this library provides should be immutable. If we still some which are not immutable, then we should fix that. 

We should promote [`TypeMapper` API](https://github.com/flink-extended/flink-scala-api?tab=readme-ov-file#type-mapping) to implement own serializers. Essentially, serializers should not be mutable, I do not see any reason to have them mutable inside.

**Comment by sonowz** [comment]
So are you saying that this library should not have mixed use with thread-unsafe `TypeSerializer`s? If so, I think it'd be better to be stated somewhere in the README that this library doesn't support thread-unsafe things, to prevent concurrency bugs caused by unintended use cases :)

**Comment by novakov-alexey** [comment]
Right. Do you have any compelling reasons to have `TypeSerializers` for Scala types which needs to have mutable state in it?

Anyway, I have looked at  that place a little bit more and found Flink API to let a user us know when serializer is not immutable, so that we clone it.

https://github.com/flink-extended/flink-scala-api/pull/114/files

**Comment by sonowz** [comment]
> Do you have any compelling reasons to have TypeSerializers for Scala types which needs to have mutable state in it?

There were cases where some fields in a case class could not be serialized with this library:
1. The field type is a class, not a case class. This library only supports case classes.
2. For legacy reasons there are `java.util.Time` field in my codebase, which is not supported by this library.
3. The field type is `AnyRef`, the field is serialized using either JSON or Avro.

In these cases, I had to pass custom TypeInformation and TypeSerializers as implicit given.

**Comment by novakov-alexey** [comment]
Yes, but passing custom TypeInformation and TypeSerializers as implicit given is ok and correct way to add serialization for the user types. I do not understand what is the reason to have mutable serializers and potentially not thread-safe for java.util.Time, for Java classes and AnyRef?

In general, serialization is inherently a process with two functions:
from my Object -> Array[Byte]
Array[Byte] -> to my Object

Why would you need to have some shared state in serializer? Do you want to count (keep track) something within a serlializer to share that state between its applications?

**Comment by sonowz** [comment]
> Why would you need to have some shared state in serializer?

Yeah I wish all serializers are implemented as thread-safe, not having shared state. However, the reality is that many TypeSerializers in Flink are written as having shared state, for example, [PojoSerializer](https://github.com/apache/flink/blob/beb0b167bdcf95f27be87a214a69a174fd49d256/flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java#L71) and [AvroSerializer](https://github.com/apache/flink/blob/beb0b167bdcf95f27be87a214a69a174fd49d256/flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSerializer.java#L60-L61).

If I were to write a custom TypeSerializer, I would definitely write it not to have shared state. However, I thought we cannot guarantee that any other users take those TypeSerializers above as an example and write it (or just copy-paste it) to have shared state.

As Scala DataStream API is being deprecated, I saw this library a go-to for all Scala users whom uses Flink, and wanted it to be as versatile as possible, and cover all the weird use cases. That's the reason why I insisted that just making all TypeSerializers in this library as thread-safe (no shared state), would not work for all cases.

**Comment by novakov-alexey** [comment]
I see, understood. Thanks for explanation! I think we are good now.

**Comment by sonowz** [comment]
Yep, thanks for supporting all the works!
I think #111 can be closed now.

**Pull request merged**
